-- 코드를 입력하세요
SELECT S.INGREDIENT_TYPE, SUM(S.TOTAL_ORDER) AS TOTAL_ORDER
FROM (
    SELECT I.FLAVOR, I.INGREDIENT_TYPE, F.TOTAL_ORDER
    FROM FIRST_HALF F
    JOIN ICECREAM_INFO I
    WHERE I.FLAVOR = F.FLAVOR
    ) AS S
GROUP BY S.INGREDIENT_TYPE
ORDER BY 2