-- 코드를 입력하세요
SELECT S.CATEGORY, S.MAX_PRICE, D.PRODUCT_NAME
FROM FOOD_PRODUCT D
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
) AS S
WHERE D.CATEGORY = S.CATEGORY
AND D.PRICE = S.MAX_PRICE
ORDER BY 2 DESC;